### ISSUE TITLE
Bring TodoTable Code back

### ISSUE THREAD

**Issue by YootTanA** [PaulBratslavsky/plugindev-intro-video-3-resources#2]
Hi PaulBratslavsky, I'm teaching my student to build a Strapi plugin right now. I wonder if you could bring back the TodoTable code. I have managed to check the commit changes. But I still curious about your decisions to left the code like the below image.

![image](https://github.com/user-attachments/assets/abf00285-c427-4ac1-b857-2d812aefe6a0)

Thank you.

**Comment by PaulBratslavsky** [comment]
@YootTanA thanks for letting me know, you can find the code here https://github.com/PaulBratslavsky/plugindev-intro-video-3-resources/edit/master/src/plugins/todo/admin/src/components/TodoTable/index.js

I will also update it in the readme file.

**Comment by YootTanA** [comment]
Thank you for keep maintaining these useful resources.
